# Generated by Django 4.2.16 on 2024-12-16 00:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_post_date_posted_post_created_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
