# Generated by Django 4.2.16 on 2025-05-22 22:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_post_likes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_on"]},
        ),
        migrations.AlterField(
            model_name="post",
            name="featured_image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default="https://res.cloudinary.com/dyemjyefz/image/upload/v1746738213/me3fmm8fozl2y69fd4xd.jpg",
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
    ]
